#! /bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

grep -v "^[[:space:]]*$"                         |
sed 's/$/ sentenceends\n/'                       |
hfst-proc2 -t 1 $DIR/tokenize.pmatch.hfst        |
grep -v "^$"                                     |
grep -v "^[|]$"                                  |
sed 's/sentenceends//' 
