#! /bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/ftb-tokenize                                                          |
sed 's/^$/<<s>>/'                                                          | 
$DIR/hfst-optimized-lookup --time-cutoff .1 -n 25 $DIR/morphology.ftb1.ol  |
sed 's/<<s>>	+?/&\n/'                                                   |
$DIR/merge_analyses.py                                                     |
sed 's/"<<<s>>>"/"<<s>>"/'                                                 |
grep -v "<s> Sent noabc"                                                   |
$DIR/replace_analyses.py                                                   |
$DIR/sort_cohorts.py